<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xmlns="http://maven.apache.org/POM/4.0.0"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
  <artifactId>org</artifactId>
  <build>
    <plugins>
      <plugin>
        <artifactId>maven-compiler-plugin</artifactId>
        <configuration>
          <release>21</release>
        </configuration>
        <groupId>org.apache.maven.plugins</groupId>
        <version>3.11.0</version>
      </plugin>
      <plugin>
        <artifactId>maven-surefire-plugin</artifactId>
        <configuration>
          <argLine>
            -javaagent:"${settings.localRepository}/org/aspectj/aspectjweaver/${aspectj.version}/aspectjweaver-${aspectj.version}.jar"
          </argLine>
          <suiteXmlFiles>
            <suiteXmlFile>test-suite.xml</suiteXmlFile>
          </suiteXmlFiles>
        </configuration>
        <groupId>org.apache.maven.plugins</groupId>
        <version>3.2.5</version>
      </plugin>
      <plugin>
        <artifactId>maven-clean-plugin</artifactId>
        <configuration>
          <filesets>
            <fileset>
              <directory>${project.basedir}/allure-results</directory>
            </fileset>
            <fileset>
              <directory>${project.build.directory}/allure-results</directory>
            </fileset>
          </filesets>
        </configuration>
        <groupId>org.apache.maven.plugins</groupId>
        <version>3.5.0</version>
      </plugin>
    </plugins>
  </build>
  <dependencies>
    <dependency>
      <artifactId>selenide</artifactId>
      <groupId>com.codeborne</groupId>
      <version>7.9.4</version>
    </dependency>
    <dependency>
      <artifactId>slf4j-simple</artifactId>
      <groupId>org.slf4j</groupId>
      <version>2.0.17</version>
    </dependency>
    <dependency>
      <artifactId>logback-classic</artifactId>
      <groupId>ch.qos.logback</groupId>
      <version>1.4.14</version>
    </dependency>
    <dependency>
      <artifactId>testng</artifactId>
      <groupId>org.testng</groupId>
      <scope>test</scope>
      <version>7.11.0</version>
    </dependency>
    <dependency>
      <artifactId>json</artifactId>
      <groupId>org.json</groupId>
      <version>20240303</version>
    </dependency>
    <dependency>
      <artifactId>webdrivermanager</artifactId>
      <groupId>io.github.bonigarcia</groupId>
      <version>6.2.0</version>
    </dependency>
    <dependency>
      <artifactId>lombok</artifactId>
      <groupId>org.projectlombok</groupId>
      <scope>provided</scope>
      <version>1.18.38</version>
    </dependency>
    <dependency>
      <artifactId>allure-testng</artifactId>
      <groupId>io.qameta.allure</groupId>
      <version>2.29.1</version>
    </dependency>
    <dependency>
      <artifactId>aspectjweaver</artifactId>
      <groupId>org.aspectj</groupId>
      <scope>runtime</scope>
      <version>${aspectj.version}</version>
    </dependency>
  </dependencies>
  <groupId>org</groupId>
  <modelVersion>4.0.0</modelVersion>

  <name>Selenide</name>

  <properties>
    <aspectj.version>1.9.21.2</aspectj.version>
    <maven.compiler.release>21</maven.compiler.release>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
  </properties>

  <version>0.0.1-SNAPSHOT</version>
</project>
