name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
      
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven

    - name: Install Docker
      run: |
        scoop bucket add extras
        scoop install docker
        docker --version

    - name: Start Selenium Grid
      run: docker-compose up -d

    - name: Wait for Selenium Hub
      run: |
          echo "Waiting for Selenium Grid to start..."
          for i in {1..15}; do
              STATUS=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:4444/status || echo "000")
              if [ "$STATUS" -eq 200 ]; then
                  echo "Selenium Grid is up!"
                  break
              fi
              sleep 2
          done

    - name: Run Tests in Parallel
      run: mvn clean test

